name: "Feature Request"
description: Propose new functionality or improvements
title: "[Feature] Short description of the feature"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ✨ **Got a new feature idea? This is the place!**

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Describe the feature you'd like to see added.
      placeholder: "I'd like to add recurring events support..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: How would this feature help users? What problem does it solve?
    validations:
      required: false

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Optional: Ideas for implementation
      description: Any thoughts on how it could be built or integrated?
