name: "New Event Submission"
description: Submit a new event to be added
title: "[Event] Title of the event"
labels: [event]
body:
  - type: markdown
    attributes:
      value: |
        📅 **Fill out the following details to the best of your abilities.**

        Paste your event in the format below (make sure to edit the fields!):

        ```
        {
          date: "yyyy-mm-dd",
          time: "6:30 PM",
          finish_time: "8:30 PM",
          title: "",
          location: "",
          country: "",
          coordinates: { longitude: "", latitude: "" },
          cost: "",
          audience: "",
          description: "",
          event_type: "",
          link: "",
          women_focussed: "✅❌",
        },
        ```

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Add anything else you'd like us to know about this event.
      placeholder: "This is a collaborative event with another group..."
    validations:
      required: false
