name: Update Courses and Events from Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # every hour on the hour

jobs:
  fetch_courses_and_events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r cloud_integration/requirements.txt

      - name: Decode credentials from secret
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > cloud_integration/credentials.json

      # Fetch and append courses
      - name: Run fetch_learning_submissions.py
        working-directory: cloud_integration
        run: python fetch_learning_submissions.py

      - name: Run append_to_courses.py
        working-directory: cloud_integration
        run: python append_to_courses.py

      # Fetch and append events
      - name: Run fetch_event_submissions.py
        working-directory: cloud_integration
        run: python fetch_event_submissions.py

      - name: Run append_to_events.py
        working-directory: cloud_integration
        run: python append_to_events.py

      - name: Commit updated data files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add courses.json js/events.json
          git commit -m "Update courses and events JSON from Google Sheets" || echo "No changes"
          git push
